### ISSUE TITLE
Adding places data?

### ISSUE THREAD

**Issue by urialon** [idandrd/israel-covid19-data#1]
Hey, 
Thanks for sharing this repo!

Can you add the textual description of each patient's route, including the places they had been to?

For example, it can be an un-parsed string of "13:00-15:00 Restaurant X, 15:00-17:00 Hotel Y"
Thanks!

**Comment by idandrd** [comment]
Hey,
We don't deal with that kind of information, but you can find it in [this excellent repo](https://github.com/oferb/israelcoronamap)
