### ISSUE TITLE
Add deceased age distribution

### ISSUE THREAD

**Issue by omrihar** [idandrd/israel-covid19-data#10]
Since the official Telegram channel reports the ages of the deceased alongside the messages about their demise, it might be beneficial to track that as well. This can allow to perform an analysis that takes the age distribution of the population into account more fully.

Thanks for the effort collecting this repo! It's great!

**Comment by guy4261** [comment]
We can manually extract this from the Telegram channel ourselves  
https://t.me/MOHreport

First case is `3314` so you can start from here: https://t.me/s/MOHreport?after=3313

I'll open a Google Spreadsheet later, but anyway here are the first cases. More columns can be added (such as the reporting hospital).

First death is considered to be an 88 y/o male at 20.03:  
https://www.ynet.co.il/articles/0,7340,L-5699076,00.html


```
20.3
88
m
https://t.me/MOHreport/3314

27.3
93
m
https://t.me/MOHreport/3446

27.3
76
f
https://t.me/MOHreport/3447

29.3
92
m
https://t.me/MOHreport/3495

29.3
84
f
https://t.me/MOHreport/3502

1.4
98
f
https://t.me/MOHreport/3589

1.4
69
f
https://t.me/MOHreport/3604
```

**Comment by idandrd** [comment]
Hey, you're right, this indeed sounds an important and interesting data to look at.
I started collecting manually and honestly, it just took me too long. The MOH doesn't report each death, so I have to look at Ynet and other sources.
@guy4261 if you have the data I'll be happy to add it to the repo!

**Comment by guy4261** [comment]
I've started manually, it was indeed too long.

Today I spent some time on the Telegram API. ~~If by any chance you already did that and can dump all the posts to some sqlite.db file or csv/tsv or whatever, that would be wonderful.~~ Most of the answers I've found were related to the versions of a Python package called `telethon` but here's the answer I based on, which works with the new API without using `async`/`await`: https://stackoverflow.com/a/54278468/2064085

~~I'll share the data once I'll have something, promise!~~

Here's `id_to_dict` pickled: 
[MOHreport_3314_3888.pkl.zip](https://github.com/idandrd/israel-covid19-data/files/4465227/MOHreport_3314_3888.pkl.zip)

Here's how I obtained it!

```python
"""Based on https://stackoverflow.com/a/54278468/2064085"""
import pickle
import telethon  # pip install telethon
from telethon.sync import TelegramClient


# because that's the version I used
assert tuple(map(int, telethon.__version__.split("."))) >= (1, 11, 3)

# Get things from https://my.telegram.org , you'll need your phone
api_id  = 1234567
api_hash  = 'bunch0fKun5t'

# https://t.me/s/MOHreport?after=3313 - 3314 is the first corona report
chat = "MOHreport"
min_id = 3313
name = 'SessionNameWhichCanBeAnythingAtAll'

id_to_dict = {}

with TelegramClient(name, api_id, api_hash) as client:
    for message in client.iter_messages(chat, min_id=min_id):
        id_to_dict[message.id] = message.to_dict()

with open("MOHreport_3314_3888.pkl", 'wb') as f:
    pickle.dump(id_to_dict, f)

# and to read it:
with open("MOHreport_3314_3888.pkl", 'rb') as f:
    foo = pickle.load(f)
```

Thanks for your efforts! 🙇

**Comment by guy4261** [comment]
Hey, forget about it -they published it themselves: https://t.me/MOHreport/3884

[‎⁨נפטרים 11-04-2020 15-06-18 (4).xlsx.xlsx⁩.xlsx.zip](https://github.com/idandrd/israel-covid19-data/files/4465246/11-04-2020.15-06-18.4.xlsx.xlsx.xlsx.zip)

@omrihar can you close?

**Comment by idandrd** [comment]
Got it!
[https://covid19data.co.il/#deaths-age-dist](https://covid19data.co.il/#deaths-age-dist)
