### ISSUE TITLE
It is not clear from the web page when the data was last updated

### ISSUE THREAD

**Issue by yenale** [idandrd/israel-covid19-data#11]

**Comment by idandrd** [comment]
Hey, thanks for the feedback.
In the graphs that contain a date, this should indicate the last update.
In the rest of the graphs, we'll make a better effort to indicate the last update time.

**Comment by makelinux** [comment]
I suggest to insert new data into the head of the file in descending order. It looks like blog.

**Comment by yenale** [comment]
Some graphs have last updated time in their description, I think it would be clearer to have this line even in graphs that contain a date (it also provides more accurate date).
keep up the good work!

**Comment by idandrd** [comment]
I see the value in what you are suggesting, but it will cause the update process to be much slower for us. Since we update multiple times a day, we must keep the process fast and easy.
