### ISSUE TITLE
Historical test data?

### ISSUE THREAD

**Issue by mikeage** [idandrd/israel-covid19-data#14]
Is it possible to expose historical test data? I.e., a CSV with date added to the initial column, so that instead of doing something like `git log cities-by-size.csv` and then `git checkout` on each update, just exposing the all historical data at once?

**Comment by idandrd** [comment]
I want to make sure I understand your need correctly - you want a file similar to CityData.csv, with tests count instead of confirmed cases count?
If so we can add such file

**Comment by mikeage** [comment]
Yes, that would work. My first thought was to duplicate each row of cities-by-size for each date (well, every two days on average), but having one source of truth and reducing duplication (such as the fields like percentage positive) is a better idea. So yes, CityData.csv with test quantities.

**Comment by liltruth** [comment]
Sadly, duplicating the rows will ruin our graph in Datawrapper.
We will consider adding a tests by city file, this is a lot of work - going back and and logging this data.

**Comment by mikeage** [comment]
Fair enough; that makes sense. I've been extracting it myself with a loop of git checkouts over git log, but I understand that it's a bit of pain.
