### ISSUE TITLE
Tested data-source is not update

### ISSUE THREAD

**Issue by kman3d** [idandrd/israel-covid19-data#16]
Hi,
https://covid19data.co.il/ "Total Patients Tested" have data of 24-Apr.
but the Corona-Tests.csv last updated on 22-Apr.

Keep up the great job!!

**Comment by liltruth** [comment]
Hey,
we moved the testing data to the main file of IsraelCOVID19.csv to make it easier to update, and the Corona-Tests file will be deleted. We will update the front page later.
Thanks!
