### ISSUE TITLE
Hebrew encoding issue

### ISSUE THREAD

**Issue by kman3d** [idandrd/israel-covid19-data#19]
Column names with Hebrew chars in the last update were corrupted
FROM: ,New Cases,בינוני M 
TO: New Cases,������

![image](https://user-images.githubusercontent.com/64000699/81922536-f0028300-95e4-11ea-8491-aca519a814c4.png)
#

**Comment by liltruth** [comment]
We know, I accidentally pushed a bad unicoded csv, we're on it.

**Comment by liltruth** [comment]
Fixed
