### ISSUE TITLE
Add spread coefficient - helps understand if the distancing works

### ISSUE THREAD

**Issue by guysoft** [idandrd/israel-covid19-data#2]
Hey,
Can we add a graph showing the delta aka:
(Number of people infected)/(people (infected the day before).

This gives a coefficient that if is greater that 1 means we are in exponential growth. So we hope it will go down as social distancing takes effect.
Video about the math:
https://www.youtube.com/watch?v=Kas0tIxDvrg&t=16

**Comment by idandrd** [comment]
done.
[here](https://covid19data.co.il/#cases-growth-factor)

**Comment by guysoft** [comment]
Hey seems like its not updating cc @idandrd

**Comment by liltruth** [comment]
> Hey seems like its not updating cc @idandrd

I can assure you we update as soon as there is data. Unfortunately the MOH has not updated data on number of people tested for several days now, so updated normalised coefficient is not available until then.

**Comment by guysoft** [comment]
Perhaps we should open an issue at: https://github.com/MohGovIL/hamagen-react-native

**Comment by guysoft** [comment]
Cc @MohGovIL any chance updating your data?

**Comment by liltruth** [comment]
> Perhaps we should open an issue at: https://github.com/MohGovIL/hamagen-react-native

Testing has nothing to do with HaMagen app data and owners, and asking MOH to update has not worked so far on our side.
