### ISSUE TITLE
Source to trace back testing observations

### ISSUE THREAD

**Issue by edomt** [idandrd/israel-covid19-data#20]
Hi @idandrd 

As you're aware, we at @owid are using your repo as input for our [coronavirus testing dataset](https://github.com/owid/covid-19-data/tree/master/public/data/). Thank you again for your efforts!

Recently we've tried checking a few random observations for various countries for which we're relying on external GitHub repos. For Israel, we've tried to check the observation for 5th April, which is 9279 new tests / 117581 total tests [in your file](https://github.com/idandrd/israel-covid19-data/blob/master/Corona-Tests.csv).

It's been a bit difficult since the only place that the official data is published is Telegram (as far as we know), but we finally managed to get access to the two PowerPoint presentations released on 5th April, and we weren't able to find any data for testing at all in them. But of course our lack of understanding of Hebrew makes this even harder. Are we checking in the wrong place?

Thanks for your help,
Edouard

**Comment by liltruth** [comment]
Hi,
You're checking in the correct place, but the MOH changed the way they released the data about the tests several times, in several picture jpg formats. We have it in the general csv updated up to June 2nd.
Ruth
