### ISSUE TITLE
showing the growth factor in moving average

### ISSUE THREAD

**Issue by orisharf** [idandrd/israel-covid19-data#5]
The growth factor data is very volatile. I think it will be better to calculate moving average for 3-4 days to reduce the volatility shown in the current graph. In this way we could see the trend (if there is any) in the growth factor.

**Comment by ohadroz** [comment]
Hey.
I think that the data in the 
growth factor is giving the wrong pic.
The data should be normalized with the total tests done every day. 
I think you need to dived the Percent Positive Patients of following days.
Otherwise as long as the number of test will grow the positives will grow and it will be always greater than 1

**Comment by idandrd** [comment]
Thanks for your feedback.
We took @ohadroz 's idea so now the data in the graph is normalized.

**Comment by idandrd** [comment]
@orisharf as for introducing a moving average - we see the advantages of this method, however we don't feel comfortable using statistics tools and including our own assumptions while creating the charts. We try to play with the data as little as possible.

**Comment by ohadroz** [comment]
Hey.

Thanks.
I have seen the update.
You have done a great job.
Two things I have noticed:
1. On the Percent Positive Patients graph the tested today data is only how
many tests were taken that day not how many tests were sloved that day or
how many people received the results. Havent seen that data on the heath
office. I think you should add note to the graph.
2. I think you should add to the
Severity of Hospitalised Patient by Date the recoverred people as well.

Best regards
