### ISSUE TITLE
Hospitalizations status and information

### ISSUE THREAD

**Issue by MaozGelbart** [idandrd/israel-covid19-data#6]
Hi there, awesome work! Especially considering that MOH does not share anywhere scrape-able on the web this data.. 

Are you open to add the usual information attached to the MOH publications regarding the hospitalized cases? To be more specific, I mean in addition to number of cases, add the number of hospitalized cases, number of ICU cases (these are cases that are classified as "hard") and number of deaths per date? Also, number of recovered cases. If you're open, I can probably provide a PR with past data so you only need to track new data. 
The rationale behind this is that this data can help to track the occupancy of the health care system in response to COVID-19. 

Many thanks!

**Comment by idandrd** [comment]
Hey @MaozGelbart, thanks for your feedback!
We just added this graph [here](https://covid19data.co.il/#severity-by-date)
