### ISSUE TITLE
This link should redirect to the github page instead of "#"

### ISSUE THREAD

**Issue by adisarid** [idandrd/israel-covid19-data#7]
In here
https://github.com/idandrd/israel-covid19-data/blob/82af572bea664cdd18af8a907032d8bf4acc04bd/www/index.html#L184

Makes more sense to use:

```
<a href="https://github.com/idandrd/israel-covid19-data" target="_blank">כאן</a>
```

Other than that, keep up the good work!!

**Comment by idandrd** [comment]
Fixed, thanks!
