### ISSUE TITLE
Possibility to split the CSV into 3 different files?

### ISSUE THREAD

**Issue by ldti** [idandrd/israel-covid19-data#8]
One for Infected, one for recovered and one for deceased?
this is (unfortunately) for importing it into Grafana...

**Comment by idandrd** [comment]
Hey,
Thanks for the feedback, but we're not going to do that because:
1. Other people are already using our data in the current format, changing it might break their code
2. This will be less comfortable for us both in updating the data and to use it in our graph system

**Comment by ldti** [comment]
Understood.



Sent from my Samsung Galaxy smartphone.



-------- Original message --------
